- name: Install NGINX
  hosts: light
  handlers:
    - name: Nginx start
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
    - name: Nginx reload
      become: true
      command: nginx -s reload
  tasks:
    - name: Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
      tags:
        - light
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Nginx start
      tags:
        - light
    - name: Create nginx config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: Nginx reload
      tags:
        - light
- name: Lighthouse | Install lighthouse
  hosts: light
  handlers:
    - name: Nginx reload
      become: true
      command: nginx -s reload
  pre_tasks:
    - name: Lighthouse | Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
      tags:
        - light
  tasks:
    - name: Lighthouse | Clone repository
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_url }}"
        dest: "{{ lighthouse_dir }}"
        version: master
      tags:
        - light
    - name: Lighthouse | Create Lighthouse config
      become: true
      ansible.builtin.template:
        src: light.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: 0644
      notify: Nginx reload
      tags:
        - light
  
