---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse 

- src: git@github.com:MikhailChervyakov/vector.git
  scm: git
  version: "main"
  name: vector

- src: git@github.com:MikhailChervyakov/lighthouse.git
  scm: git
  version: "main"
  name: lighthouse